apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: my-namespace
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort